### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by jackpoz** [pnp/blog#101]
#### Question

I've been following the previous blog using RSS feeds, available on the homepage at https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/bg-p/Microsoft365PnPBlog

![image](https://user-images.githubusercontent.com/1153754/165262786-75027e66-6e0d-426d-9a4e-dfec58ff6986.png)

Are RSS feeds supported by the new blog platform ? I understand that there are social media and github notifications, still checking if I missed the link somewhere.

**Comment by LuiseFreese** [comment]
Dear @jackpoz - thank you for raising this issue - it's great feedback. It's now on the list of things to implement, will keep you posted.

**Comment by appieschot** [comment]
Will pick this one up.

**Comment by appieschot** [comment]
@jackpoz the RSS made a return and can be accessed again ;-) Let us know if it fits your needs!

**Comment by jackpoz** [comment]
Thanks, I added it to the RSS feed reader and it seems to work 😃

**Comment by LuiseFreese** [comment]
Great to hear! 🚀

**Comment by appieschot** [comment]
Awesome, will have a look at support for Feedly images as well as I just saw that is missing ;-)
