### ISSUE TITLE
Implement twitter cards

### ISSUE THREAD

**Issue by appieschot** [pnp/blog#124]
#### Article issue

The template currently does not render the header image when posting a link to twitter. We should update our template to provide the required OpenGraph or Twitter info to render images propperly. 

We can use https://cards-dev.twitter.com/validator to validate our current template.

**Comment by appieschot** [comment]
I'll pick this one up, for future reference: 

Remove the following snippet to fall back to custom implementation 
 https://github.com/pnp/blog/blob/1c05096b6f8a83cbf6ff005b0427761eb506a21f/themes/reader-hugo/layouts/partials/head.html#L77-L78

Rewrite to use correct image (currently using the svg logo) 
 https://github.com/pnp/blog/blob/1c05096b6f8a83cbf6ff005b0427761eb506a21f/themes/reader-hugo/layouts/partials/head.html#L46-L75

**Comment by LuiseFreese** [comment]
hey @appieschot  can you please only change the files in the blog/layouts folder and not in the blogs/themes/reader-hugo/layouts folder? This way we don't override the theme. This was @hugoabernier s suggestion :-)

**Comment by appieschot** [comment]
Will look into it, we should be able to do I think 🦾

**Comment by appieschot** [comment]
@hugoabernier do you want me to revert #127 and implement a custom file in the `/layouts` folder as well? That way we could keep the reader-hugo as is I guess?

**Comment by LuiseFreese** [comment]
that would be perfect!

**Comment by appieschot** [comment]
Solved with last PR, cards should be visible now.
