### ISSUE TITLE
Implement BACK button from blog to main site

### ISSUE THREAD

**Issue by LuiseFreese** [pnp/blog#155]
Right now there is no way to get from https://pnp.github.io/blog to https://pnp.github.io, our main landing page.

**Comment by LuiseFreese** [comment]
Hey @Adam-it - thank you! I think it would be nice if it matches the experience that people have on the PnP landing page https://pnp.github.io? 

![image](https://user-images.githubusercontent.com/49960482/181439504-d8fda6d7-048e-47eb-996a-03df023bc3ba.png)

**Comment by Adam-it** [comment]
I'll try to do my best. 
Assigning myself to this one then 👍

**Comment by LuiseFreese** [comment]
you go!!
