### ISSUE TITLE
Optimize link checking action

### ISSUE THREAD

**Issue by appieschot** [pnp/blog#202]
Currently our link checking action fails with some errors (see for instance: https://github.com/pnp/blog/actions/runs/2320281477)

- 95 errors (59 errors on YouTube error code; random check does load these videos)
- 103 timeouts (56 on adoption.microsoft.com and 46 on aka.ms/extensibility)

It feels like we can do some optimization to minimize the amount of errors: 

- [x] Either Exclude https://aka.ms/m365/extensibility from checking 
- [x] Either exclude adoption.microsoft.com, or increase timeout 
- [x] Set a `--max-concurrency <max-concurrency>` setting to less then 128 so we do not get errors on YouTube (looks like they block after an no amount of requests

After that is done there should be around 50'ish issues left that we then can manually check. Once all issues are solved we could op to fail the build if a new faulty link is introduced. Or scan our repository on a daily base and auto create new issues for breaking links.

**Comment by LuiseFreese** [comment]
Excluding both links is an excellent idea, also exclude graph.microsoft.com links, as they all return 401 usually, similar with xxx.sharepoint.com 

Right now I would not let the build fail but output the broken link as an issue so that we can work on that. 


🚀🚀🚀 Thank you!

**Comment by appieschot** [comment]
We are now down to 29 errors (from 135) and the `.lycheeignore` file is cleaned up. Before implementing the creation of issues I suggest we take a look at the content and solve those 29 errors as well (feels like we can fix some of those by fixing the content before we randomly exclude them ;-)). 

Once we are down to zero broken links we should turn on the auto creation of issues.

**Comment by appieschot** [comment]
9 Issues left. Weekend time first now

**Comment by LuiseFreese** [comment]
Sorry just thick thumbs on mobile 🧐
