### ISSUE TITLE
Top Level Folder from Document Library - PnP Modern Search

### ISSUE THREAD

**Issue by kartrabby** [pnp/blog#402]
Hello, can anyone please help me on this. I am using PnP Modern Search ( V4 ). This is how my Document library looks like

![image](https://user-images.githubusercontent.com/95188375/176666850-dc6857b6-b079-4dd9-b879-cc586d315335.png)

But the below Query Template fetches all Top Folders, subfolders and Files.

Path:"https://you-sharepoint-site-here/Shared%20Documents/"
{searchTerms} (ParentLink:{/Documents/})

This is the result of the above Query Template

![image](https://user-images.githubusercontent.com/95188375/176667044-e9c6bee0-cb39-4423-abb4-23f7c2f66996.png)

Please help me to get only Top Level Folder from Document Library ( what is the Query Template ) ?

Just like this ?

![image](https://user-images.githubusercontent.com/95188375/176667106-cd87ee6a-9b65-40c5-a358-e88620a971ad.png)

**Comment by LuiseFreese** [comment]
Hi there, 

May I point you to the [PnP Modern Search](https://github.com/microsoft-search/pnp-modern-search/) repo? Hope that you find someone there to help you with this question :-)
