### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by alex-mclachlan-silverbear** [pnp/blog#429]
#### Article issue

https://github.com/pnp/blog/blob/main/CONTRIBUTING.md has a link to https://github.com/pnp/blog/blob/main/content/post%5Cwhat-s-up-with-markdown.md on line 77 which give a 404 error.

I believe the link should be to https://pnp.github.io/blog/post/what-s-up-with-markdown/

**Comment by LuiseFreese** [comment]
fixed  in PR #431
