### ISSUE TITLE
is CONTRIBUTING.md up to date?

### ISSUE THREAD

**Issue by Adam-it** [pnp/blog#53]
#### is CONTRIBUTING.md up to date?
Hi,

I wanted to contribute a new article post with a PR to this repo but I noticed that in the https://github.com/pnp/blog/blob/main/CONTRIBUTING.md
point 8 we have:
![image](https://user-images.githubusercontent.com/58668583/160291957-d614f3fa-ff58-436a-a9b4-d519f4205ffa.png)

but checking the repo contents I noticed we rather store Images in the same location where we keep the blog post.
For example
![image](https://user-images.githubusercontent.com/58668583/160292027-e098a0a1-c25a-42a8-aad1-63bf50554142.png)

Not sure if I understood this properly but seems just not inconsistent 🤔.
Would you mind if I open a small PR and correct this guidance? or maybe you want to do it yourself with a quick commit 😉? Or maybe it is ok, and I just don't understand it properly 😋 (in that case sorry for the stupid question 😉)

**Comment by LuiseFreese** [comment]
hey @Adam-it  we needed to change the approach to make it easier for people to contribute, and you as an early adopter already noticed this :-) 

We appreciate your help, please PR :-) 

You rock! 🚀

**Comment by Adam-it** [comment]
So it's a new thing... that's cool 👍. I don't know if my opinion counts but IMO a step in the good direction 😎. Maybe now when I won't need to leave VS code to add a blog post I will try to contribute even more 😋.
I am writing a new post even now so I will go over the contribution guide point by point and if I will notice anything else I will also include it in this PR (which I will try to open today during late night 😉).
BTW thanks ... [I always wanted to rock ](https://www.youtube.com/watch?v=2-ptLktOjrY)🤩🤩
