### ISSUE TITLE
Suggestion: clean up tags & rendering

### ISSUE THREAD

**Issue by andrewconnell** [pnp/blog#579]
#### Suggestion

Hugo applies sentence-casing to multi-word tags. This creates tags that are incorrect for branding/products. For example:

- "SharePoint Framework (SPFx)" renders to **SharePoint framework (SPFx)**
- "Office AddIns" renders to **Office add ins**
- "Azure DevOps" renders to **Azure devops**

This creates incorrect tags regardless of what the author of the post picked. 

It can be fixed by adding a new subfolder `/tags` and entering the desired rendering. Hugo will then use the title of the tag in the tag's **_index.md** file when rendering it on the site. For instance, without this, you can't control how Hugo lists tags.

This is how I control the tag text rendering on my sites ([andrewconnell.com](https://www.andrewconnell.com) & [voitanos.io](https://www.voitanos.io). For example, without this, the tag "CloudDev Clarity" would render as "Clouddev clarity".

![Screen Shot 2022-09-15 at 5 39 50 AM](https://user-images.githubusercontent.com/2068657/190371813-9b54278a-a576-42a5-9314-d1e7b11c6aa9.png)
![Screen Shot 2022-09-15 at 5 43 09 AM](https://user-images.githubusercontent.com/2068657/190371985-71265272-20d3-4810-83a7-1820a012aa6f.png)

If someone adds a new tag to a post that hasn't been fixed up, Hugo just defaults to it's normal behavior, so the worst-case scenario is the current behavior.

I can take this enhancement on if you like... just assign the issue to me.

**Comment by appieschot** [comment]
Sounds like a great improvement assigned to you!
