### ISSUE TITLE
🐞 SEO bug with OG tags in header

### ISSUE THREAD

**Issue by andrewconnell** [pnp/blog#580]
Current rendering is duping OG tags in page head across site, including hard-coded incorrect references.

REF: 
![Screen Shot 2022-09-15 at 5 57 34 AM](https://user-images.githubusercontent.com/2068657/190375887-d58cad06-d6ff-4d44-b006-7fc6dc7d746f.png)

Specficially:

- `og:url`
- `og:type`

I can fix if you want... assign task to me.

**Comment by appieschot** [comment]
@andrewconnell would be awesome if you want to pick this one up 🦾
