### ISSUE TITLE
broken img src

### ISSUE THREAD

**Issue by Adam-it** [pnp/blog#64]
#### How to set image in the article .md file properly?
Hi 👋 I think last time I did something wrong 😉 and in my last post https://pnp.github.io/blog/post/save-data-to-app-personal-folder/ the image src attrs are broken 
![image](https://user-images.githubusercontent.com/58668583/163064069-d1eca14d-fcad-4666-860c-0d5b05f9468c.png)

I've done it this way
```
{{< image alt="requestToAppRoot.png" src="images/requestToAppRoot.png" >}}
```
Could you point me in the right direction 🤔? 

BTW I have one bonus question 😉.
is this repo somehow connected also with the techcommunity blog? I see that some articles that are present here
https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/bg-p/Microsoft365PnPBlog 
are also present https://pnp.github.io/blog but not the other way around 🤔? If I would like to have the same article in both places I should add it separately ?

**Comment by LuiseFreese** [comment]
Hey @Adam-it 

I always insert images with `![Alt text of the image](/images/this-is-my-image.png)` . I know @hugoabernier  did some short code magic behind the scenes, but either we are using it wrong (most likely) or it stopped working for some reason. 

Can y9ou try to insert your image in markdown syntax as shown above? 

Answering your bonus question:

We are in the middle of transitioning from TC to GH and getting everyone on speed plus polishing last bits. Stay tuned :-)

**Comment by Adam-it** [comment]
Ok thanks for your comment 👍. Will update the article to fix the pictures and for now also add the article to the techcommunity page 👍
